######################################################################################
### rstream-crtmpd.conf
## tag: _TAG_
######################################################################################
CRTMPD_ENABLE=_CRTMPD_ENABLE_
CRTMPD_BIN="_CRTMPD_BIN_"
CRTMPD_RTMP_IP="_CRTMPD_RTMP_IP_"
CRTMPD_RTMP_PORT="_CRTMPD_RTMP_PORT_"
CRTMPD_LIVEFLV_IP="_CRTMPD_LIVEFLV_IP_"
CRTMPD_LIVEFLV_PORT="_CRTMPD_LIVEFLV_PORT_"
CRTMPD_PROXY_ENABLE="_CRTMPD_PROXY_ENABLE_"
CRTMPD_PROXY_URL="_CRTMPD_PROXY_URL_"
CRTMPD_PROXY_LSTREAM="_CRTMPD_PROXY_LSTREAM_"
CRTMPD_PROXY_DSTREAM="_CRTMPD_PROXY_DSTREAM_"
CRTMPD_PROXY_TRANSPARENT="_CRTMPD_PROXY_TRANSPARENT_"
CRTMPD_REGEN_CONF=_CRTMPD_REGEN_CONF_