#!/bin/sh
######################################################################################
### rstream-freebsd9_ffmpeg-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi


ffmpegServiceCreate() {
	if [ -z $1 ]; then echo "!! missing stream name, exiting !!"; exit 99; fi
	stream=$1
	checkDir $HOME/var/log/ffmpeg -c rstream 700
	checkDir $HOME/var/supervise/ffmpeg-nginx-${stream}/log -c rstream 755
	echo "*+ generating new ffmpeg/run script for stream \"$stream\"";
	cat $HOME/include/templates/ffmpeg-run.tpl \
		| sed s,_HOME_,$HOME,g \
		| sed s,_USER_,$USER,g \
		| sed s,_STREAM_,$stream,g \
		| sed s,_DAEMON_,'nginx',g \
		> $HOME/var/supervise/ffmpeg-nginx-${stream}/run
		chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/run
	echo "*+ generating new ffmpeg/run/log script for stream \"$stream\"";
	cat $HOME/include/templates/ffmpeg-run-log.tpl \
		| sed s,_HOME_,$HOME,g \
		| sed s,_USER_,$USER,g \
		> $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
		chmod 755 $HOME/var/supervise/ffmpeg-nginx-${stream}/log/run
}

ffmpeg-router() {
	if [ -z $1 ]; then routeHelp; exit 1; fi
	logRoute "ffmpeg" $1 
	if [ -z $FFMPEG_ENABLE ] || [ ! $FFMPEG_ENABLE -eq 1 ]; then break; fi

	case $1 in
		create) ffmpegServiceCreate $2;;
		link) rstream-router "-link";;
	esac
}