#!/bin/sh
######################################################################################
### rstream-freebsd9_daemontools-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; exit 2; fi

####
### daemontools Setup
####
daemontoolsSetup(){
	logHeader "daemontools setup"
	# check if daemontools is installed
	checkDependency "daemontools"
	# check if services exist
	checkDir $DAEMONTOOLS_SERVICE -rc
	# enable daemontools
	enableRc "svscan"
}


####
### daemontools Link Services
####
daemontoolsLinkServices(){
	if [ ! -h $2/$1 ]; then
		echo "*+ creating service link for \"$1\" in \"$2\"";
		ln -s $HOME/var/supervise/$1 $2/
		if [ ! $? -eq 0 ]; then echo "!! error !!"; exit 99; fi
	else
		echo "* found daemontools service in $2/$1";
	fi
}

####
### daemontools Router
####
daemontools-router(){
	if [ -z $1 ]; then routeHelp; exit 1; fi
	logRoute "daemontools" $1 
	case $1 in
		setup) daemontoolsSetup;;
		status|stat)
			echo "* checking if svscan is running"
			service svscan status
		;;
		stop)
			echo "* stopping svscan"
			echo "* cleaning old lock files in \"$HOME/rstream/tmp/ffmpeg/*.lock\""
			#rm -f $HOME/tmp/ffmpeg/*.lock
			service svscan stop
		;;
		start)
			echo "* starting svscan"
			service svscan start
			echo "** Sleeping 5 seconds..."
			sleep 5
		;;
		restart)
			daemontools-router "stop"
			daemontools-router "start"
		;;
		*) routeHelp;;
	esac
}

