#!/bin/sh
######################################################################################
### rstream-config-crtmpd-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

logHeader "* entering crtmpd config helper"

CRTMPD_BIN="/usr/local/bin/crtmpserver"
CRTMPD_RTMP_IP=""
CRTMPD_RTMP_PORT=""
CRTMPD_LIVEFLV_IP=""
CRTMPD_LIVEFLV_PORT=""
CRTMPD_REGEN_CONF="1"

askCrtmpdBin(){
	logHeader "General config"
	echo -n "Where is your crtmpserver binary ? "
	read tmp
	if [ ! -f $tmp ]; then echo "!! cannot find crtmpserver binary in $tmp !!"; askCrtmpdBin;
	else CRTMPD_BIN=$tmp; fi
}
if [ -z $CRTMPD_BIN ]; then askCrtmpdBin; fi

askRTMP(){
	logHeader "RTMP config"
	echo -n "What IP address should crtmpd use to listen to incoming and outgoing RTMP connections [x.x.x.x] ? "
	read CRTMPD_RTMP_IP

	echo -n "What PORT should crtmpd use to listen to incoming and outgoing RTMP connections on $CRTMPD_RTMP_IP [1935] ? "
	read CRTMPD_RTMP_PORT
	if [ -z $CRTMPD_RTMP_PORT ]; then CRTMPD_RTMP_PORT=1935; fi

	echo "** Are these settings correct ?"
	echo "- crtmpd RTMP IP: $CRTMPD_RTMP_IP"
	echo "- crtmpd RTMP PORT: $CRTMPD_RTMP_PORT"
	echo -n "[y/n] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askRTMP;;
	esac
}
if [ -z $CRTMPD_RTMP_IP ] || [ -z $CRTMPD_RTMP_PORT ]; then askRTMP; fi

askProxyData(){
	logHeader "PROXY Push config"

	echo -n "To what rtmp://user:pass@host:port/:app should we push the current stream to ? "
	read CRTMPD_PROXY_URL
	if [ -z $CRTMPD_PROXY_URL ]; then askProxyData; fi

	echo -n "What local stream should we push to $CRTMPD_PROXY_URL [test] ? "
	read CRTMPD_PROXY_LSTREAM
	if [ -z $CRTMPD_PROXY_LSTREAM ]; then CRTMPD_PROXY_LSTREAM="test"; fi

	echo -n "As what destination stream name should we push local stream \"$CRTMPD_PROXY_LSTREAM\" to  \"$CRTMPD_PROXY_URL\" [$CRTMPD_PROXY_LSTREAM] ? "
	read CRTMPD_PROXY_DSTREAM
	if [ -z $CRTMPD_PROXY_DSTREAM ]; then CRTMPD_PROXY_DSTREAM=$CRTMPD_PROXY_LSTREAM; fi

	echo "** Are these settings correct ?"
	echo "- crtmpd PROXY URL: $CRTMPD_PROXY_URL"
	echo "- crtmpd PROXY LOCAL STREAM: $CRTMPD_PROXY_LSTREAM"
	echo "- crtmpd PROXY DESTINATION STREAM: $CRTMPD_PROXY_DSTREAM"
	echo -n "[y/n] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askProxyData;;
	esac
}
echo -n "Do you want to enable PUSH style PROXY [y/N] ? "
read tmp
case $tmp in
	y|Y) CRTMPD_PROXY_ENABLE=1;;
	*) CRTMPD_PROXY_ENABLE=0;;
esac

if [ ! -z $CRTMPD_PROXY_ENABLE ] && [ $CRTMPD_PROXY_ENABLE -eq 1 ]; then
	if [ -z $CRTMPD_PROXY_URL ] || [ -z $CRTMPD_PROXY_LSTREAM ] || [ -z $CRTMPD_PROXY_DSTREAM ]; then askProxyData; fi
fi

askLIVEFLV(){
	logHeader "LIFE FLV config (required for transcoding)"
	echo -n "What IP address should crtmpd use to listen to incoming transcoded LIVE FLV connections [$CRTMPD_RTMP_IP] ? "
	read CRTMPD_LIVEFLV_IP
	if [ -z $CRTMPD_LIVEFLV_IP ]; then CRTMPD_LIVEFLV_IP=$CRTMPD_RTMP_IP; fi

	echo -n "What PORT should crtmpd use to listen to incoming transcoded LIVE FLV connections on $CRTMPD_LIVEFLV_IP [21935] ? "
	if [ ! -z $CRTMPD_RTMP_PORT ]; then echo -n "! Do not use $CRTMPD_RTMP_PORT ! "; fi
	read CRTMPD_LIVEFLV_PORT
	if [ -z $CRTMPD_LIVEFLV_PORT ]; then CRTMPD_LIVEFLV_PORT=21935; fi

	echo "** Are these settings correct ?"
	echo "- crtmpd LIVE-FVL IP: $CRTMPD_LIVEFLV_IP"
	echo "- crtmpd LIVE-FLV PORT: $CRTMPD_LIVEFLV_PORT"
	echo -n "[y/n] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askLIVEFLV;;
	esac
}
if [ $FFMPEG_ENABLE -eq 1 ]; then
	if [ -z $CRTMPD_LIVEFLV_IP ] || [ -z $CRTMPD_LIVEFLV_PORT ]; then askLIVEFLV; fi
fi
