#!/bin/sh
######################################################################################
### rstream-config-hls-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

logHeader "* entering HLS config helper"

#CRTMPD_BIN="$HOME/src/crtmpserver-trunk-x86_64-FreeBSD-9.0/crtmpserver"
HLS_WWW="$HOME/tmp/hls/nginx"
HLS_FQDN=""
HLS_TYPE="nginx"

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

askHLSFQDN(){
	host=`hostname`
	echo -n "What FQDN will be serving the HLS streams [http://$hostname] ? "
	read tmp
	if [ -z $tmp ]; then HLS_FQDN="htt://$host/hls/nginx";
	else HLS_FQDN=$tmp; fi
}
if [ ! -z $NGINX_ENABLE ]; then askHLSFQDN; fi

