#!/bin/sh
######################################################################################
### rstream-config-crtmpd-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi
if [ ! -f $CRTMPD_BIN ]; then echo "!! error, crtmpd not found, exiting !!"; exit 99; fi 

logSection "* entering crtmpd config helper"

CRTMPD_RTMP_IP=""
CRTMPD_RTMP_PORT=""
CRTMPD_LIVEFLV_IP=""
CRTMPD_LIVEFLV_PORT=""
CRTMPD_REGEN_CONF="1"

askCrtmpdBin(){
	logSection "General config"
	echo -n "Where is your crtmpserver binary ? "
	read tmp
	if [ ! -f $tmp ]; then echo "!! cannot find crtmpserver binary in $tmp !!"; askCrtmpdBin;
	else CRTMPD_BIN=$tmp; fi
}
if [ -z $CRTMPD_BIN ]; then askCrtmpdBin; fi

askRTMP(){
	logSection "RTMP config"
	
	echo -n "What IP address should crtmpd use to listen to incoming and outgoing RTMP connections [$HOST_IP] ? "
	read CRTMPD_RTMP_IP
	if [ -z $CRTMPD_RTMP_IP ]; then CRTMPD_RTMP_IP=$HOST_IP; fi

	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then port=1936; else port=1935; fi
	echo -n "What PORT should crtmpd use to listen to incoming and outgoing RTMP connections on $CRTMPD_RTMP_IP [$port] ? "
	read CRTMPD_RTMP_PORT
	if [ -z $CRTMPD_RTMP_PORT ]; then CRTMPD_RTMP_PORT=$port; fi

	echo "** Are these settings correct ?"
	echo "- crtmpd RTMP IP: $CRTMPD_RTMP_IP"
	echo "- crtmpd RTMP PORT: $CRTMPD_RTMP_PORT"
	echo -n "[y/N] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askRTMP;;
	esac
}
if [ -z $CRTMPD_RTMP_IP ] || [ -z $CRTMPD_RTMP_PORT ]; then askRTMP; fi

askProxyData(){
	logSection "PROXY Push config"

	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then rtmp_host="rtmp://$CRTMPD_RTMP_IP:1935/r"
	else rtmp_host="rtmp://user:pass@host:port/app"; fi
	echo -n "To what rtmp address should we push the current stream to [$rtmp_host] ? "
	read CRTMPD_PROXY_URL
	if [ -z $CRTMPD_PROXY_URL ]; then CRTMPD_PROXY_URL=$rtmp_host; fi

	echo -n "Do you want to enable proxy transparentStream mode ? (implies you patched crtmpd !) ? [y/N] "
	read CRTMPD_PROXY_TRANSPARENT
	case $tmp in
		y|Y) CRTMPD_PROXY_TRANSPARENT=1;;
		n) CRTMPD_PROXY_TRANSPARENT=0;;
		*) askProxyData;;
	esac

	if [ -z $CRTMPD_PROXY_TRANSPARENT ] || [ ! $CRTMPD_PROXY_TRANSPARENT -eq 1 ]; then
		echo -n "What local stream should we push to $CRTMPD_PROXY_URL [test] ? "
		read CRTMPD_PROXY_LSTREAM
		if [ -z $CRTMPD_PROXY_LSTREAM ]; then CRTMPD_PROXY_LSTREAM="test"; fi
	
		echo -n "As what destination stream name should we push local stream \"$CRTMPD_PROXY_LSTREAM\" to \"$CRTMPD_PROXY_URL\" [$CRTMPD_PROXY_LSTREAM] ? "
		read CRTMPD_PROXY_DSTREAM
		if [ -z $CRTMPD_PROXY_DSTREAM ]; then CRTMPD_PROXY_DSTREAM=$CRTMPD_PROXY_LSTREAM; fi
	fi

	echo "** Are these settings correct ?"
	echo "- crtmpd PROXY URL: $CRTMPD_PROXY_URL"
	if [ -z $CRTMPD_TRANSPARENT_STREAM ] || [ ! $CRTMPD_TRANSPARENT_STREAM -eq 1 ]; then
		echo "- crtmpd PROXY LOCAL STREAM: $CRTMPD_PROXY_LSTREAM"
		echo "- crtmpd PROXY DESTINATION STREAM: $CRTMPD_PROXY_TRANSPARENT"
	else
		echo "- CRTMPD_PROXY_TRANSPARENT is enabled in crtmpd !"
	fi
	echo -n "[y/N] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askProxyData;;
	esac
}
echo -n "Do you want to enable PUSH style PROXY [y/N] ? "
read tmp
case $tmp in
	y|Y) CRTMPD_PROXY_ENABLE=1;;
	*) CRTMPD_PROXY_ENABLE=0;;
esac

if [ ! -z $CRTMPD_PROXY_ENABLE ] && [ $CRTMPD_PROXY_ENABLE -eq 1 ]; then
	if [ -z $CRTMPD_PROXY_URL ] || [ -z $CRTMPD_PROXY_LSTREAM ] || [ -z $CRTMPD_PROXY_DSTREAM ]; then askProxyData; fi
fi

askLIVEFLV(){
	logSection "LIFE FLV config (required for transcoding)"
	echo -n "What IP address should crtmpd use to listen to incoming transcoded LIVE FLV connections [$CRTMPD_RTMP_IP] ? "
	read CRTMPD_LIVEFLV_IP
	if [ -z $CRTMPD_LIVEFLV_IP ]; then CRTMPD_LIVEFLV_IP=$CRTMPD_RTMP_IP; fi

	echo -n "What PORT should crtmpd use to listen to incoming transcoded LIVE FLV connections on $CRTMPD_LIVEFLV_IP [21935] ? "
	if [ ! -z $CRTMPD_RTMP_PORT ]; then echo -n "! Do not use $CRTMPD_RTMP_PORT ! "; fi
	read CRTMPD_LIVEFLV_PORT
	if [ -z $CRTMPD_LIVEFLV_PORT ]; then CRTMPD_LIVEFLV_PORT=21935; fi

	echo "** Are these settings correct ?"
	echo "- crtmpd LIVE-FVL IP: $CRTMPD_LIVEFLV_IP"
	echo "- crtmpd LIVE-FLV PORT: $CRTMPD_LIVEFLV_PORT"
	echo -n "[y/N] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askLIVEFLV;;
	esac
}
#if [ ! -z $FFMPEG_CRTMPD_ENABLE ] && [ $FFMPEG_CRTMPD_ENABLE -eq 1 ]; then
#	if [ -z $CRTMPD_LIVEFLV_IP ] || [ -z $CRTMPD_LIVEFLV_PORT ]; then askLIVEFLV; fi
#fi
