#!/bin/sh
######################################################################################
### rstream-config-hls-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

logHeader "* entering HLS config helper"

HLS_WWW="$HOME/shared/www"
HLS_FQDN=""
HLS_TYPE="nginx"
HLS_PATH="$HOME/tmp/nginx"

askHLSFQDN(){
	host=`hostname`
	echo -n "What FQDN will be serving the HLS streams [http://$hostname] ? "
	read tmp
	if [ -z $tmp ]; then HLS_FQDN="htt://$host/hls/nginx";
	else HLS_FQDN=$tmp; fi
}
if [ ! -z $NGINX_ENABLE ]; then askHLSFQDN; fi
