#!/bin/sh
######################################################################################
### rstream-confg-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

RSTREAM_TYPE=""
FFMPEG_ENABLE=""
HLS_ENABLE=""
FFMPEG_NGINX_TRANSCODING=""
FFMPEG_CRTMPD_TRANSCODING=""

####
### Start the installer logic
####
rstream-config(){
	logHeader "* loading config-helper";
	
	CONFIG_FILE=$HOME/etc/rstream.conf
	CRTMPD_ENABLE=""
	NGINX_ENABLE=""
	askServers(){
	echo ""
	echo "* What type of setup do you want ?"
	echo "1. crtmpserver only"
	echo "2. nginx-rtmp only"
	echo "3. crtmpserver AND nginx-rtmp"
	echo -n "[1/2/3] "
	read tmp
	
	case $tmp in
		1) CRTMPD_ENABLE=1;;
		2) NGINX_ENABLE=1;;
		3) CRTMPD_ENABLE=1; NGINX_ENABLE=1;;
		*) askServers;;
	esac
	}

	setHostIp

	if [ -z $CRTMPD_ENABLE ] && [ -z $NGINX_ENABLE ]; then askServers; fi

	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then . $HOME/include/rstream-config/rstream-config-crtmpd-helper;fi
	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then . $HOME/include/rstream-config/rstream-config-nginx-helper;fi
	# hls only works with nginx for now.
	. $HOME/include/rstream-config/rstream-config-hls-helper
	. $HOME/include/rstream-config/rstream-config-ffmpeg-helper


	genConf	
}


genConf(){
	backupFile $CONFIG_FILE

	touch $CONFIG_FILE;

	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then
		cat  $HOME/include/templates/rstream-conf-crtmpd.tpl >> $CONFIG_FILE 
		cat $CONFIG_FILE \
			| sed s,_TAG_,$TAG,g \
			| sed s,_CRTMPD_BIN_,$CRTMPD_BIN,g \
			| sed s,_CRTMPD_ENABLE_,$CRTMPD_ENABLE,g \
			| sed s,_CRTMPD_REGEN_CONF_,$CRTMPD_REGEN_CONF,g \
			| sed s,_CRTMPD_RTMP_IP_,$CRTMPD_RTMP_IP,g \
			| sed s,_CRTMPD_RTMP_PORT_,$CRTMPD_RTMP_PORT,g \
			| sed s,_CRTMPD_LIVEFLV_IP_,$CRTMPD_LIVEFLV_IP,g \
			| sed s,_CRTMPD_LIVEFLV_PORT_,$CRTMPD_LIVEFLV_PORT,g \
			| sed s,_CRTMPD_PROXY_ENABLE_,$CRTMPD_PROXY_ENABLE,g \
			| sed s,_CRTMPD_PROXY_URL_,$CRTMPD_PROXY_URL,g \
			| sed s,_CRTMPD_PROXY_TRANSPARENT_,$CRTMPD_PROXY_TRANSPARENT,g \
			| sed s,_CRTMPD_PROXY_LSTREAM_,$CRTMPD_PROXY_LSTREAM,g \
			| sed s,_CRTMPD_PROXY_DSTREAM_,$CRTMPD_PROXY_DSTREAM,g \
		> $CONFIG_FILE.tmp && mv $CONFIG_FILE.tmp $CONFIG_FILE
	fi

	if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then
		cat  $HOME/include/templates/rstream-conf-nginx.tpl >> $CONFIG_FILE 
		cat $CONFIG_FILE \
			| sed s,_TAG_,$TAG,g \
			| sed s,_NGINX_BIN,$NGINX_BIN,g \
			| sed s,_NGINX_ENABLE_,$NGINX_ENABLE,g \
			| sed s,_NGINX_REGEN_CONF_,$NGINX_REGEN_CONF,g \
			| sed s,_NGINX_RTMP_IP_,$NGINX_RTMP_IP,g \
			| sed s,_NGINX_RTMP_PORT_,$NGINX_RTMP_PORT,g \
			| sed s,_NGINX_RTMP_STREAM_,$NGINX_RTMP_STREAM,g \
		> $CONFIG_FILE.tmp && mv $CONFIG_FILE.tmp $CONFIG_FILE
	fi

	if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then
		cat  $HOME/include/templates/rstream-conf-nginx-hls.tpl >> $CONFIG_FILE 
		cat $CONFIG_FILE \
			| sed s,_TAG_,$TAG,g \
			| sed s,_HLS_ENABLE_,$HLS_ENABLE,g \
			| sed s,_HLS_FQDN_,$HLS_FQDN,g \
			| sed s,_HLS_TYPE_,$HLS_TYPE,g \
			| sed s,_HLS_PATH_,$HLS_PATH,g \
			| sed s,_HLS_WWW_,$HLS_WWW,g \
			| sed s,_HLS_STREAM_,$HLS_STREAM,g \
			| sed s,_TAG_,$TAG,g \
		> $CONFIG_FILE.tmp && mv $CONFIG_FILE.tmp $CONFIG_FILE
	fi
	if [ ! -z $FFMPEG_ENABLE ] && [ $FFMPEG_ENABLE -eq 1 ]; then
		cat  $HOME/include/templates/rstream-conf-transcoder.tpl >> $CONFIG_FILE 
		cat $CONFIG_FILE \
			| sed s,_TAG_,$TAG,g \
			| sed s,_FFMPEG_ENABLE_,$FFMPEG_ENABLE,g \
			| sed s,_FFMPEG_TRANSCODER_IP_,$FFMPEG_TRANSCODER_IP,g \
			| sed s,_FFMPEG_CRTMPD_ENABLE_,$FFMPEG_CRTMPD_ENABLE,g \
			| sed s,_FFMPEG_NGINX_ENABLE_,$FFMPEG_NGINX_ENABLE,g \
		> $CONFIG_FILE.tmp && mv $CONFIG_FILE.tmp $CONFIG_FILE
	fi
}
