#!/bin/sh
######################################################################################
### rstream-config-nginx-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

logHeader "* entering nginx-rtmp config helper"

NGINX_RTMP_FQDN=""
NGINX_RTMP_IP=""
NGINX_RTMP_PORT=""

NGINX_RTMP_IP=""
NGINX_RTMP_PORT=""
NGINX_REGEN_CONF="1"


askRTMP(){
	logHeader "General config"
	if [ -z $CRTMPD_RTMP_IP ]; then tmp="x.x.x.x"; else tmp=$CRTMPD_RTMP_IP; fi
	echo -n "What IP address should nginx-rtmp use to listen to incoming and outgoing RTMP connections [$tmp] ? "
	read NGINX_RTMP_IP
	if [ -z $NGINX_RTMP_IP ] && [ ! -z $CRTMPD_RTMP_IP ]; then NGINX_RTMP_IP=$CRTMPD_RTMP_IP; fi
	if [ -z $NGINX_RTMP_IP ] && [ -z $CRTMPD_RTMP_IP ]; then askRTMP; fi

	echo -n "What PORT should nginx-rtmp use to listen to incoming and outgoing RTMP connections on $NGINX_RTMP_IP [1935] ? "
	read NGINX_RTMP_PORT
	if [ -z $NGINX_RTMP_PORT ]; then NGINX_RTMP_PORT=1935; fi

	echo "** Are these settings correct ?"
	echo "- nginx-rtmp RTMP IP: $NGINX_RTMP_IP"
	echo "- nginx-rtmp RTMP PORT: $NGINX_RTMP_PORT"
	echo -n "[y/n] "
	read tmp
	case $tmp in
		y|Y) echo "* ok";;
		*) askRTMP;;
	esac
}
if [ -z $NGINX_RTMP_IP ] || [ -z $NGINX_RTMP_PORT ]; then askRTMP; fi
