#!/bin/sh
######################################################################################
### rstream-config-ffmpeg-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

logHeader "* entering FFMPEG config helper"

FFMPEG_TRANSCODER_IP=""

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

askFFMPEGIP(){
	logHeader "General config"
	if [ -z $CRTMPD_RTMP_IP ]; then tmp="x.x.x.x"; else tmp=$CRTMPD_RTMP_IP; fi
	echo -n "What source IP address will ffmpeg use when connecting to transcoding destinations [$tmp] ? "
	read FFMPEG_TRANSCODER_IP
	if [ -z $FFMPEG_TRANSCODER_IP ] && [ ! -z $CRTMPD_RTMP_IP ]; then FFMPEG_TRANSCODER_IP=$CRTMPD_RTMP_IP; fi
	if [ -z $FFMPEG_TRANSCODER_IP ] && [ -z $CRTMPD_RTMP_IP ]; then askFFMPEGIP; fi
}
if [ ! -z $FFMPEG_ENABLE ]; then askFFMPEGIP; fi
