#!/bin/sh
######################################################################################
### rstream-freebsd9_daemontools-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not suppoesd to execute this file directly"; routerHelp; exit 2; fi

####
### daemontools Setup
####
daemontoolsSetup(){
	logHeader "daemontools setup"
	# check if daemontools is installed
	checkDependency "daemontools"
	# check if services exist
	checkDir $DAEMONTOOLS_SERVICE -rc
	# enable daemontools
	enableRc "svscan"
}



####
### daemontools Router
####
daemontoolsRouter(){
	if [ -z $1 ]; then routeHelp; exit 1; fi
	logRoute "daemontools" $1 
	case $1 in
		setup)
			daemontoolsSetup
		;;
		status|stat)
			echo "* checking if svscan is running"
			service svscan status
		;;
		stop)
			echo "* stopping svscan"
			service svscan stop
		;;
		start)
			echo "* starting svscan"
			service svscan start
			daemontoolsRouter "status"
		;;
		restart)
			daemontoolsRouter "stop"
			daemontoolsRouter "start"
		;;
		*) 
			routeHelp
		;;
	esac
}