#!/bin/sh
######################################################################################
### rstream-core
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routeHelp; exit 2; fi

## Used for log consmetics
logRoute(){
	echo "";
	echo ">> route \"$1/$2\"";
}
logHeader(){
	echo "** $1";
}
logSection(){
	echo "";
	echo ">> $1"
}
## Used to link configuration file $1 to path $2 (and backups $2 if it is a file)
linkConf(){
	# test if $2 is a file, not a symblink
	if [ ! -h $2 ] && [ -f $2 ]; then
		echo "*+ backuping file \"$1\"";
		backupFile $1
		if [ ! $? -eq 0 ]; then echo "!! error !!"; exit 99; fi
	fi
	if [ ! -h $2 ]; then
		echo "*+ linking \"$1\" to \"$2\""
		ln -s $1 $2
		if [ ! $? -eq 0 ]; then echo "!! error !!"; exit 99; fi
	else
		echo "* found existing link from \"$1\" to \"$2\"";
	fi
}





####
### Services
####
setupServices(){
	logHeader="services setup"
	OLD_IFS=$IFS;
IFS="
"
	if [ -z $DAEMONTOOLS_SERVICE ] || [ ! -d $DAEMONTOOLS_SERVICE ]; then echo "!! error invalid DAEMONTOOLS_SERVICE \"$DAEMONTOOLS_SERVICE\", existing."; exit 99; fi
	# testing if link to crtmpd service exists
	for i in `ls -1 $HOME/var/supervise`; do
			daemontoolsLinkServices $i $DAEMONTOOLS_SERVICE
	done
#	if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then
#	fi
}

debugCycle(){
	pauseTime=3
	~rstream/bin/rstream -debug-reset && sleep $pauseTime \
	&& ~rstream/bin/rstream -setup crtmpd-proxy-to-nginx && sleep $pauseTime \
	&& ~rstream/bin/rstream -link && sleep $pauseTime \
	&& ~rstream/bin/rstream restart
}

debugReset(){
	logHeader="debug reset"
	cmd="rm -rf $HOME/tmp"
	cmd="$cmd && rm -rf $HOME/var"
	cmd="$cmd && rm -rf $HOME/shared"
	cmd="$cmd && rm -f $HOME/etc/nginx*"
	cmd="$cmd && rm -f $HOME/etc/crtmpd*"
	cmd="$cmd && rm -f $DAEMONTOOLS_SERVICE/crtmpd"
	echo "-! Are you sure you want to execute:"
	echo $cmd;
	echo "[y/N]"
	read debug_confirmation
	case $debug_confirmation in
		[yY]) rstream-core-route "stop"; echo ""; echo "* Cleaning up.." `$cmd`;;
		*) echo "!! User-canceled reset" exit 1;;
	esac
}


routeHelp(){
	echo "!! error, no valid argument(s) specified !"
	echo "-! please consult the documentation: https://github.com/kelexel/rstream";
}

rstream-core-init(){
	logHeader "- init checks"
	# check if our main $USER exists
	checkUser $USER $HOME;
	# check $HOME strucutre
	checkDir $HOME/etc -c $USER 755
	checkDir $HOME/var/log -c $USER 755
	checkDir $HOME/shared/media -c $USER
	checkDir $HOME/shared/www -c $USER 755
	checkDir $HOME/tmp -c
}

rstream-core-route(){
	# check for config file
	checkFile $HOME/etc/rstream.conf 1
	if [ -z $1 ]; then routeHelp; exit 1; fi
	case $1 in
		stop)
			daemontoolsRouter "stop"
			killall -u $USER
			killall -TERM readproctitle supervise multilog crtmpserver
		;;
		start)
			checkServiceEnabled crtmpd -nn
			checkServiceEnabled nginx -nn
			checkServiceEnabled svscan -y
			daemontoolsRouter "start"
			rstream-core-route "status"
		;;
		restart)
			rstream-core-route "stop"
			rstream-core-route "start"
		;;
		stat|status)
			daemontoolsRouter "status";
			if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then crtmpdRouter "status"; fi
			if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then nginxRouter "status"; fi
		;;
		-link) setupServices;;
		-crtmp|-crtmpd)
			if [ -z $2 ]; then route; exit 99; fi
			crtmpdRouter $2
		;;
		-nginx)
			if [ -z $2 ]; then route; exit 99; fi
			nginxRouter $2
		;;
		-daemontools|svscan)
			daemontoolsRouter $2
		;;
		-debug-cycle) debugCycle;;
		-debug-reset) debugReset;;
		-config)
			if [ -f $HOME/etc/rstream.conf ]; then 
				echo "Woops found an already existing $HOME/etc/rstream.conf - backuping"
				backupFile $HOME/etc/rstream.conf;
				rstream-init
			fi

		;;
		-setup|-install)
			if [ ! -f $HOME/etc/rstream.conf ]; then
				rstream-config
			else
#				rstream-core-route "stop"
				if [ ! -z $CRTMPD_ENABLE ] && [ $CRTMPD_ENABLE -eq 1 ]; then
					crtmpdRouter "setup"
				fi
				if [ ! -z $NGINX_ENABLE ] && [ $NGINX_ENABLE -eq 1 ]; then
					nginxRouter "setup"
					daemontoolsRouter "setup"
				fi
			fi
		;;
		*) routeHelp; exit 1;;
	esac
}