#!/bin/sh
######################################################################################
### rstream-freebsd9_nginx-helper
# 
# license: GPL
# 
# authors:
# - Rudolph Sand aka https://github.com/kelexel
# 
# url:
# - https://github.com/kelexel/rstream
#
#######################################################################################

if [ -z $TAG ]; then echo "!! Error you are not supposed to execute this file directly"; routerHelp; exit 2; fi

####
### Nginx setup
####
nginxSetup(){
	logHeader "nginx setup"
	# test if nginx is installed
	checkDependency "nginx"
	nginx_bin=`which nginx` # should result in /usr/local/bin/nginx
	# test if nginx was compiled with nginx-rtmp support
	if [ ! `$nginx_bin -V 2>&1 | grep -q rtmp; echo $?` -eq 0 ]; then echo "!! nginx was not compiled with nginx-rtmp support , existing."; exit 99; fi
	echo "* found nginx-rtmp support";
	# test if nginx was compiled with nginx-rtmp/hls support
	if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ] && [ ! `$nginx_bin -V 2>&1 | grep -q hls;  echo $?` -eq 0 ]; then echo "!! nginx was not compiled with nginx-rtmp/hls support , existing."; exit 99; 
		else if [ ! -z $HLS_ENABLE ] && [ $HLS_ENABLE -eq 1 ]; then echo "* found nginx-rtmp/hls support"; fi
	fi
	# set nginx_conf to default FreeBSD nginx port config location
	LINKED_CONF="/usr/local/etc/nginx/nginx.conf"
	NGINX_CONF="$HOME/etc/nginx-rtmp.conf"
	# set NGINX_CONF_TPL based on $NGINX_HLS
	NGINX_CONF_TPL=${HOME}/include/templates/nginx-conf.tpl
	if [ $NGINX_REGEN_CONF -eq 1 ]; then echo "-! enforcing NGINX_REGEN_CONF"; fi
	if [ $NGINX_REGEN_CONF -eq 1 ] || [ ! -f $NGINX_CONF ]; then
		echo "*+ generating new nginx conf";
		# generate local nginx conf
		cat $NGINX_CONF_TPL \
			| sed s,_HOME_,$HOME,g \
			| sed s,_NGINX_RTMP_IP_,$NGINX_RTMP_IP,g \
			| sed s,_NGINX_RTMP_PORT_,$NGINX_RTMP_PORT,g \
			| sed s,_NGINX_RTMP_STREAM_,$NGINX_RTMP_STREAM,g \
			> $NGINX_CONF
	fi
	# link nginx conf
	linkConf $NGINX_CONF $LINKED_CONF
	# only make the following tests if NGINX_HLS is set to 1
	if [ $HLS_ENABLE ]; then
		# set nginx_mime_types to default FreeBSD nginx port config location
		nginx_mime_types="/usr/local/etc/nginx/mime.types"
		# link mime types
		linkConf $HOME/etc/nginx-rtmp-mime.types $nginx_mime_types

		echo "*+ enabling HLS in nginx configuration"
		cat $NGINX_CONF \
			| sed s,_HLS_ENABLE_,$HLS_ENABLE,g \
			| sed s,_HLS_FQDN_,$HLS_FQDN,g \
			| sed s,_HLS_TYPE_,$HLS_TYPE,g \
			| sed s,_HLS_WWW_,$HLS_WWW,g \
			| sed s,_HLS_STREAM_,$HLS_STREAM,g \
			| sed s,"#HLS","",g \
		> $NGINX_CONF.tmp && mv $NGINX_CONF.tmp $NGINX_CONF
	fi
	if [ $FFMPEG_ENABLE ]; then
		echo "*+ enabling HLS in nginx configuration"
		cat $NGINX_CONF \
			| sed s,_FFMPEG_TRANSCODER_IP_,$FFMPEG_TRANSCODER_IP,g \
			| sed s,"#TRANSCODING","",g \
		> $NGINX_CONF.tmp && mv $NGINX_CONF.tmp $NGINX_CONF
	fi

}	

####
### CRTMPD router
####
nginxRouter(){
	if [ -z $1 ]; then routeHelp; exit 1; fi
	logRoute "nginx" $1 
	case $1 in
		setup)
			nginxSetup
		;;
		status|stat)
			echo "* checking if svscan is running"
			service nginx status
		;;
		stop)
			echo "* stopping svscan"
			service nginx stop
		;;
		start)
			echo "* starting svscan"
			service nginx start
			nginxRouter "status"
		;;
		restart)
			nginxRouter "stop"
			nginxRouter "start"
		;;
		hls-flush)
			echo "* flushing hls directory"
			rm -f $HOME/tmp/hls/*.ts
			rm -f $HOME/tmp/hls/*.m3u8
		;;
		*) 
			routeHelp
		;;
	esac
}